import {
  PUBLIC_COMPLETION_SPEC,
  PUBLIC_GLOBAL_OPTIONS,
  completionWords
} from '../spec.js';

/**
 * Generate Fish completion script for ailock
 */
export function generateFishCompletion(): string {
  const commandLines = Object.entries(PUBLIC_COMPLETION_SPEC)
    .map(
      ([command, spec]) =>
        `complete -c ailock -n __ailock_needs_command -a ${command} -d "${spec.description}"`
    )
    .join('\n');
  const globalOptionLines = PUBLIC_GLOBAL_OPTIONS.map(option => {
    const shortFlag = option.flags.find(flag => /^-[^-]$/.test(flag));
    const longFlag = option.flags.find(flag => flag.startsWith('--'));
    const flags = [
      shortFlag ? `-s ${shortFlag.slice(1)}` : '',
      longFlag ? `-l ${longFlag.slice(2)}` : ''
    ]
      .filter(Boolean)
      .join(' ');
    return `complete -c ailock ${flags} -d "${option.description}"`;
  }).join('\n');
  const genericLines = [
    'protect',
    'auth',
    'quota',
    'edit',
    'emergency-unlock',
    'doctor',
    'hooks'
  ]
    .map(
      command =>
        `complete -c ailock -n "__ailock_using_command ${command}" -a "${completionWords(command as keyof typeof PUBLIC_COMPLETION_SPEC).join(' ')}"`
    )
    .join('\n');

  return `# ailock fish completion script
# Generated by: ailock completion fish

# Disable file completion by default
complete -c ailock -f
complete -c aiunlock -f

# Helper function to get completion suggestions
function __ailock_complete_helper
    ailock completion-helper --type $argv[1] --partial $argv[2] 2>/dev/null
end

# Check if we're using the subcommand
function __ailock_using_command
    set -l cmd (commandline -opc)
    if test (count $cmd) -gt 1
        if test $cmd[2] = $argv[1]
            return 0
        end
    end
    return 1
end

# Check if no subcommand is used yet
function __ailock_needs_command
    set -l cmd (commandline -opc)
    if test (count $cmd) -eq 1
        return 0
    end
    return 1
end

# Main commands
${commandLines}

# Global options
${globalOptionLines}

# Public subcommands and options not covered by the path-aware blocks below
${genericLines}

# init command options
complete -c ailock -n "__ailock_using_command init" -l force -d "Force overwrite existing config"
complete -c ailock -n "__ailock_using_command init" -l interactive -d "Interactive configuration setup"
complete -c ailock -n "__ailock_using_command init" -l config-only -d "Only create config file without locking"
complete -c ailock -n "__ailock_using_command init" -l with-ai-docs -d "Install AI documentation"
complete -c ailock -n "__ailock_using_command init" -l no-ai-hooks -d "Skip AI hook installation"

# lock command options and file completion
complete -c ailock -n "__ailock_using_command lock" -l verbose -d "Show detailed output"
complete -c ailock -n "__ailock_using_command lock" -l dry-run -d "Preview changes without applying"
complete -c ailock -n "__ailock_using_command lock" -l all -d "Lock all configured files"
complete -c ailock -n "__ailock_using_command lock" -l no-gitignore -d "Skip .gitignore integration"
complete -c ailock -n "__ailock_using_command lock" -l no-hooks -d "Skip automatic hook installation"
complete -c ailock -n "__ailock_using_command lock" -l hooks-only -d "Only install hooks"
complete -c ailock -n "__ailock_using_command lock" -a "(__ailock_complete_helper unlocked-files (commandline -ct))" -d "File to lock"

# unlock command options and file completion
complete -c ailock -n "__ailock_using_command unlock" -l verbose -d "Show detailed output"
complete -c ailock -n "__ailock_using_command unlock" -l dry-run -d "Preview changes without applying"
complete -c ailock -n "__ailock_using_command unlock" -l all -d "Unlock all files"
complete -c ailock -n "__ailock_using_command unlock" -l no-gitignore -d "Skip .gitignore integration"
complete -c ailock -n "__ailock_using_command unlock" -a "(__ailock_complete_helper locked-files (commandline -ct))" -d "File to unlock"

# status command options
complete -c ailock -n "__ailock_using_command status" -l verbose -d "Show detailed status"
complete -c ailock -n "__ailock_using_command status" -l simple -d "Simple output format"
complete -c ailock -n "__ailock_using_command status" -l json -d "JSON output format"
complete -c ailock -n "__ailock_using_command status" -l interactive -d "Show interactive dashboard"
complete -c ailock -n "__ailock_using_command status" -l skip-analytics -d "Skip analytics and first-run prompts"

# list command options
complete -c ailock -n "__ailock_using_command list" -l long -d "Long format with details"
complete -c ailock -n "__ailock_using_command list" -l locked-only -d "Show only locked files"
complete -c ailock -n "__ailock_using_command list" -l json -d "JSON output format"

# diagnose command options and file completion
complete -c ailock -n "__ailock_using_command diagnose" -l verbose -d "Show detailed diagnostics"
complete -c ailock -n "__ailock_using_command diagnose" -F -d "File to diagnose"

# generate command options
complete -c ailock -n "__ailock_using_command generate" -l template -r -a "github-actions gitlab-ci docker-production devcontainer" -d "Generate a specific template"
complete -c ailock -n "__ailock_using_command generate" -l category -r -a "ci-cd docker devcontainer" -d "Generate all templates in a category"
complete -c ailock -n "__ailock_using_command generate" -l list -d "List available templates"
complete -c ailock -n "__ailock_using_command generate" -l force -d "Overwrite existing files"
complete -c ailock -n "__ailock_using_command generate" -l dry-run -d "Preview without creating files"


# completion command shells
complete -c ailock -n "__ailock_using_command completion" -a bash -d "Bash shell"
complete -c ailock -n "__ailock_using_command completion" -a zsh -d "Zsh shell"
complete -c ailock -n "__ailock_using_command completion" -a fish -d "Fish shell"
complete -c ailock -n "__ailock_using_command completion" -a powershell -d "PowerShell"
complete -c ailock -n "__ailock_using_command completion" -l install-instructions -d "Show installation instructions"

# Also set up completion for aiunlock command
complete -c aiunlock -w ailock
`;
}
