import {
  PUBLIC_COMPLETION_SPEC,
  PUBLIC_GLOBAL_OPTIONS,
  completionWords
} from '../spec.js';

/**
 * Generate Zsh completion script for ailock
 */
export function generateZshCompletion(): string {
  const commandDescriptions = Object.entries(PUBLIC_COMPLETION_SPEC)
    .map(([command, spec]) => `        '${command}:${spec.description}'`)
    .join('\n');
  const globalOptions = PUBLIC_GLOBAL_OPTIONS
    .map(option => `        '{${option.flags.join(',')}}[${option.description}]' \\`)
    .join('\n');
  const genericCases = [
    'protect',
    'auth',
    'quota',
    'edit',
    'emergency-unlock',
    'doctor',
    'hooks'
  ]
    .map(command => `                ${command})
                    _arguments '*:value:(${completionWords(command as keyof typeof PUBLIC_COMPLETION_SPEC).join(' ')})'
                    ;;`)
    .join('\n\n');

  return `#compdef ailock aiunlock
# ailock zsh completion script
# Generated by: ailock completion zsh

_ailock() {
    local -a commands options
    local context state line
    
    # Define commands
    commands=(
${commandDescriptions}
    )
    
    # Main completion
    _arguments -C \\
${globalOptions}
        '1: :->command' \\
        '*:: :->args'
    
    case \$state in
        command)
            _describe -t commands 'ailock command' commands
            ;;
            
        args)
            case \$words[1] in
                init)
                    _arguments \\
                        '--force[Force overwrite existing config]' \\
                        '--interactive[Interactive configuration setup]' \\
                        '--config-only[Only create config file without locking]' \\
                        '--with-ai-docs[Install AI documentation]' \\
                        '--no-ai-hooks[Skip AI hook installation]'
                    ;;
                    
                lock)
                    _arguments \\
                        '--all[Lock all configured files]' \\
                        '--verbose[Show detailed output]' \\
                        '--dry-run[Preview changes without applying]' \\
                        '--no-gitignore[Skip .gitignore integration]' \\
                        '--no-hooks[Skip automatic hook installation]' \\
                        '--hooks-only[Only install hooks]' \\
                        '*:file:_ailock_unlocked_files'
                    ;;
                    
                unlock)
                    _arguments \\
                        '--verbose[Show detailed output]' \\
                        '--dry-run[Preview changes without applying]' \\
                        '--all[Unlock all files]' \\
                        '--no-gitignore[Skip .gitignore integration]' \\
                        '*:file:_ailock_locked_files'
                    ;;
                    
                status)
                    _arguments \\
                        '--interactive[Show interactive dashboard]' \\
                        '--verbose[Show detailed status]' \\
                        '--simple[Simple output format]' \\
                        '--json[JSON output format]' \\
                        '--skip-analytics[Skip analytics and first-run prompts]'
                    ;;
                    
                list)
                    _arguments \\
                        '--long[Long format with details]' \\
                        '--locked-only[Show only locked files]' \\
                        '--json[JSON output format]'
                    ;;
                    
                diagnose)
                    _arguments \\
                        '--verbose[Show detailed diagnostics]' \\
                        '1:file:_files'
                    ;;
                    
                generate)
                    _arguments \\
                        '--template[Generate a specific template]:template:(github-actions gitlab-ci docker-production devcontainer)' \\
                        '--category[Generate all templates in a category]:category:(ci-cd docker devcontainer)' \\
                        '--list[List available templates]' \\
                        '--force[Overwrite existing files]' \\
                        '--dry-run[Preview without creating files]'
                    ;;

${genericCases}
                    
                    
                completion)
                    local -a shells
                    shells=(bash zsh fish powershell)
                    _arguments \\
                        '1:shell:(bash zsh fish powershell)' \\
                        '--install-instructions[Show installation instructions]'
                    ;;
                
                setup-completion|help)
                    # No additional arguments for these commands
                    ;;
                    
                *)
                    # Default case - provide file completion
                    _files
                    ;;
            esac
            ;;
    esac
}

# Custom completion functions for file suggestions
_ailock_locked_files() {
    local -a files
    files=(\${(f)"\$(ailock completion-helper --type locked-files --partial \$words[CURRENT] 2>/dev/null)"})
    if [[ -n "\$files" ]]; then
        _describe -t files 'locked file' files
    else
        _files
    fi
}

_ailock_unlocked_files() {
    local -a files
    files=(\${(f)"\$(ailock completion-helper --type unlocked-files --partial \$words[CURRENT] 2>/dev/null)"})
    if [[ -n "\$files" ]]; then
        _describe -t files 'unlocked file' files
    else
        _files
    fi
}

# Ensure completion system is initialized
if ! command -v compdef &>/dev/null; then
    autoload -Uz compinit && compinit
fi

# Set up completion for both ailock and aiunlock
if command -v compdef &>/dev/null; then
    compdef _ailock ailock
    compdef _ailock aiunlock
fi

# Lazy loading support (optional)
# To enable lazy loading, wrap the function:
# _ailock_lazy() {
#     unfunction "\$0"
#     source <(ailock completion zsh)
#     _ailock "\$@"
# }
# if command -v compdef &>/dev/null; then
#     compdef _ailock_lazy ailock
#     compdef _ailock_lazy aiunlock
# fi
`;
}
